bug/minor: api spec: fix incorrect type for idp.source
we must use integer because "int" will make elabapi-python fail with:
AttributeError: module 'elabapi_python.models' has no attribute 'ModelInt'